### ISSUE TITLE
use fit_generator to load datasets

### ISSUE THREAD

**Issue by vivekpd15** [dvgodoy/deepreplay#14]
How to use this library if I am using fit_generator to load images.
My datasets are huge, so this will be needed.

Thanks in advance.

**Comment by dvgodoy** [comment]
Hi,

Unfortunately the package does not support this kind of usage.
You can still create a `ReplayData` object using the subset of data you want to visualize and it will be included in the resulting H5 file. But you cannot use a generator for this.

Hope this helps.
