### ISSUE TITLE
AttributeError: 'function' object has no attribute 'encode'

### ISSUE THREAD

**Issue by mariamjumoke** [dvgodoy/deepreplay#15]
I ran into this error while trying to fit my model and i havent been able to fix it:

AttributeError: 'function' object has no attribute 'encode'

**Comment by dvgodoy** [comment]
Hi,

I guess you are using a custom loss function, right?
I am aware of this error, but haven't fixed it yet.

If this is not the case, please provide more details about your usage.
Thanks

**Comment by mariamjumoke** [comment]
No, I used categorical cross entropy.

**Comment by dvgodoy** [comment]
Ok, so it is probably something I am not aware of... 
Could you please copy the full stack trace of the error as well as your code for model creation and training?

**Comment by dvgodoy** [comment]
Hi @mariamjumoke ,

I've just released a new version, fixing a bug with custom metrics - I've asked you about a custom loss function, but I should've asked for a custom metric.
Anyway, I hope this latest release fixes your issue.
